/**
 * Standard error codes for the application.
 */
export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  
  // Auth specific
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  
  // Tenant specific
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  INVALID_BRANCH = 'INVALID_BRANCH',
  
  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  
  // Checkout
  CART_ALREADY_CHECKED_OUT = 'CART_ALREADY_CHECKED_OUT',
  
  // Idempotency
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
}
