import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#c0272d',
        'on-primary-container': '#ffdad7',
        'primary': '#ffb3ae',
        'on-primary': '#68000c',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3ae',
        'on-primary-fixed': '#410004',
        'on-primary-fixed-variant': '#930015',
        'inverse-primary': '#b72028',
        'secondary': '#c8c6c5',
        'on-secondary': '#303030',
        'secondary-container': '#474746',
        'on-secondary-container': '#b6b5b4',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474746',
        'tertiary': '#83d0f6',
        'on-tertiary': '#003547',
        'tertiary-container': '#006d8f',
        'on-tertiary-container': '#c1e9ff',
        'tertiary-fixed': '#c0e8ff',
        'tertiary-fixed-dim': '#83d0f6',
        'on-tertiary-fixed': '#001e2b',
        'on-tertiary-fixed-variant': '#004d66',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'surface-dim': '#131313',
        'surface': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e3bebb',
        'outline': '#aa8986',
        'outline-variant': '#5a403e',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'surface-tint': '#ffb3ae',
        'surface-variant': '#353534',
        'background': '#131313',
        'on-background': '#e5e2e1',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
export default config
